server:
  port: 8081  # El puerto en el que el Gateway se va a ejecutar

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':  # Aplica CORS a todas las rutas
            allowedOrigins: "http://localhost:4200"  # Permite solicitudes desde tu frontend
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: auth
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**

        - id: products
          uri: http://localhost:8080
          predicates:
            - Path=/api/products/**

        - id: category
          uri: http://localhost:8080
          predicates:
            - Path=/api/category/**

        - id: orders
          uri: http://localhost:8080
          predicates:
            - Path=/api/orders/**

        - id: cart
          uri: http://localhost:8080
          predicates:
            - Path=/api/cart/**
        - id: kardex
          uri: http://localhost:8080
          predicates:
            - Path=/api/kardex/**
        - id: staff
          uri: http://localhost:8080
          predicates:
            - Path=/api/staff/**
        - id: staff
          uri: http://localhost:8080
          predicates:
            - Path=/api/staff/**
        - id: suppliers
          uri: http://localhost:8080
          predicates:
            - Path=/api/suppliers/**
        - id: addresses
          uri: http://localhost:8080
          predicates:
            - Path=/api/addresses/**
        - id: addresses
          uri: http://localhost:8080
          predicates:
            - Path=/api/addresses/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG  # Habilita los logs para ver el tráfico
    org.springframework.web: DEBUG
