server:
  port: 8081   # Puerto donde corre el Gateway

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      default-filters:
        - StripPrefix=1    # Quita el primer segmento (/gateway/…) antes de reenviar
      routes:
        # Autenticación: sign-up, log-in, listado y borrado de usuarios
        - id: auth
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**    # UsersController

        # Carrito: crear, obtener, agregar, eliminar producto y vaciar
        - id: cart
          uri: http://localhost:8080
          predicates:
            - Path=/api/cart/**    # CartController

        # Productos: CRUD completo + manejo de imágenes
        - id: products
          uri: http://localhost:8080
          predicates:
            - Path=/api/products/**    # ProductController

        # Categorías: CRUD
        - id: category
          uri: http://localhost:8080
          predicates:
            - Path=/api/category/**    # CategoryController

        # Proveedores: CRUD
        - id: suppliers
          uri: http://localhost:8080
          predicates:
            - Path=/api/suppliers/**   # SupplierController

        # Staff: CRUD
        - id: staff
          uri: http://localhost:8080
          predicates:
            - Path=/api/staff/**       # StaffController

        # Kardex: CRUD de movimientos de inventario
        - id: kardex
          uri: http://localhost:8080
          predicates:
            - Path=/api/kardex/**      # KardexController

        # Órdenes: test, listar, detalle, crear desde carrito y eliminar
        - id: orders
          uri: http://localhost:8080
          predicates:
            - Path=/api/orders/**      # OrderController

        # Direcciones de usuario: CRUD
        - id: addresses
          uri: http://localhost:8080
          predicates:
            - Path=/api/addresses/**   # UserAddressController
